<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="em_AU">

<head>

    <base href="<?=$this->application->url();?>" target="_top" />

    <?=$this->html->title($this->application->config->app['name']);?>

    <?=$this->import();?>

</head>
<body>

    <?=$this->layout();?>

    <?=$this->post();?>

</body>
</html>

